# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/adrian/python/fg-ai-flightplan/ScheduleViewer/ScheduleUi/MainWindow.ui'
#
# Created: Wed Oct 26 14:06:45 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 794)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.flightsTab = QtGui.QWidget()
        self.flightsTab.setObjectName("flightsTab")
        self.gridLayout_8 = QtGui.QGridLayout(self.flightsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget = QtGui.QTableWidget(self.flightsTab)
        self.tableWidget.setMinimumSize(QtCore.QSize(1055, 436))
        self.tableWidget.setMaximumSize(QtCore.QSize(3000, 3000))
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.flightsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.callsignEdit = QtGui.QLineEdit(self.groupBox)
        self.callsignEdit.setObjectName("callsignEdit")
        self.gridLayout.addWidget(self.callsignEdit, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.depAirportEdit = QtGui.QLineEdit(self.groupBox)
        self.depAirportEdit.setObjectName("depAirportEdit")
        self.gridLayout.addWidget(self.depAirportEdit, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.depTimeEdit = QtGui.QLineEdit(self.groupBox)
        self.depTimeEdit.setObjectName("depTimeEdit")
        self.gridLayout.addWidget(self.depTimeEdit, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.depDayEdit = QtGui.QLineEdit(self.groupBox)
        self.depDayEdit.setObjectName("depDayEdit")
        self.gridLayout.addWidget(self.depDayEdit, 0, 7, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 8, 1, 1)
        self.acTypeEdit = QtGui.QLineEdit(self.groupBox)
        self.acTypeEdit.setObjectName("acTypeEdit")
        self.gridLayout.addWidget(self.acTypeEdit, 0, 9, 1, 1)
        self.arrTimeEdit = QtGui.QLineEdit(self.groupBox)
        self.arrTimeEdit.setObjectName("arrTimeEdit")
        self.gridLayout.addWidget(self.arrTimeEdit, 1, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.arrAirportEdit = QtGui.QLineEdit(self.groupBox)
        self.arrAirportEdit.setObjectName("arrAirportEdit")
        self.gridLayout.addWidget(self.arrAirportEdit, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.airlineEdit = QtGui.QLineEdit(self.groupBox)
        self.airlineEdit.setObjectName("airlineEdit")
        self.gridLayout.addWidget(self.airlineEdit, 1, 1, 1, 1)
        self.showButton = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-ok-apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showButton.setIcon(icon1)
        self.showButton.setAutoDefault(False)
        self.showButton.setDefault(True)
        self.showButton.setObjectName("showButton")
        self.gridLayout.addWidget(self.showButton, 1, 7, 1, 1)
        self.clearButton = QtGui.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/user-busy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon2)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 9, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.labelTotalFlights = QtGui.QLabel(self.groupBox)
        self.labelTotalFlights.setText("")
        self.labelTotalFlights.setObjectName("labelTotalFlights")
        self.gridLayout_5.addWidget(self.labelTotalFlights, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.labelSelectedFlights = QtGui.QLabel(self.groupBox)
        self.labelSelectedFlights.setText("")
        self.labelSelectedFlights.setObjectName("labelSelectedFlights")
        self.gridLayout_5.addWidget(self.labelSelectedFlights, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.labelDuplicates = QtGui.QLabel(self.groupBox)
        self.labelDuplicates.setText("")
        self.labelDuplicates.setObjectName("labelDuplicates")
        self.gridLayout_5.addWidget(self.labelDuplicates, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findDupesButton = QtGui.QPushButton(self.groupBox)
        self.findDupesButton.setObjectName("findDupesButton")
        self.horizontalLayout.addWidget(self.findDupesButton)
        self.addButton = QtGui.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon3)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtGui.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon4)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.truncateButton = QtGui.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/system-reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.truncateButton.setIcon(icon5)
        self.truncateButton.setObjectName("truncateButton")
        self.horizontalLayout.addWidget(self.truncateButton)
        self.gridLayout_9.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.flightsTab, "")
        self.fleetTab = QtGui.QWidget()
        self.fleetTab.setObjectName("fleetTab")
        self.gridLayout_10 = QtGui.QGridLayout(self.fleetTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_2 = QtGui.QGroupBox(self.fleetTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.callsignEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.callsignEdit_fleet.setObjectName("callsignEdit_fleet")
        self.gridLayout_2.addWidget(self.callsignEdit_fleet, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 1)
        self.airlineEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.airlineEdit_fleet.setObjectName("airlineEdit_fleet")
        self.gridLayout_2.addWidget(self.airlineEdit_fleet, 1, 1, 1, 1)
        self.showButton_fleet = QtGui.QPushButton(self.groupBox_2)
        self.showButton_fleet.setIcon(icon1)
        self.showButton_fleet.setAutoDefault(False)
        self.showButton_fleet.setDefault(True)
        self.showButton_fleet.setObjectName("showButton_fleet")
        self.gridLayout_2.addWidget(self.showButton_fleet, 1, 7, 1, 1)
        self.clearButton_fleet = QtGui.QPushButton(self.groupBox_2)
        self.clearButton_fleet.setIcon(icon2)
        self.clearButton_fleet.setObjectName("clearButton_fleet")
        self.gridLayout_2.addWidget(self.clearButton_fleet, 1, 9, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.nrAircraftEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.nrAircraftEdit_fleet.setObjectName("nrAircraftEdit_fleet")
        self.gridLayout_2.addWidget(self.nrAircraftEdit_fleet, 0, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.hubsEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.hubsEdit_fleet.setObjectName("hubsEdit_fleet")
        self.gridLayout_2.addWidget(self.hubsEdit_fleet, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 4, 1, 1)
        self.acTypeEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.acTypeEdit_fleet.setObjectName("acTypeEdit_fleet")
        self.gridLayout_2.addWidget(self.acTypeEdit_fleet, 1, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 8, 1, 1)
        self.designationEdit_fleet = QtGui.QLineEdit(self.groupBox_2)
        self.designationEdit_fleet.setObjectName("designationEdit_fleet")
        self.gridLayout_2.addWidget(self.designationEdit_fleet, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 6, 1, 1)
        self.airlineComboBox = QtGui.QComboBox(self.groupBox_2)
        self.airlineComboBox.setObjectName("airlineComboBox")
        self.gridLayout_2.addWidget(self.airlineComboBox, 0, 7, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 0, 1, 1)
        self.labelTotalFleet = QtGui.QLabel(self.groupBox_2)
        self.labelTotalFleet.setText("")
        self.labelTotalFleet.setObjectName("labelTotalFleet")
        self.gridLayout_6.addWidget(self.labelTotalFleet, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 0, 1, 1)
        self.labelSelectedFleet = QtGui.QLabel(self.groupBox_2)
        self.labelSelectedFleet.setText("")
        self.labelSelectedFleet.setObjectName("labelSelectedFleet")
        self.gridLayout_6.addWidget(self.labelSelectedFleet, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_6)
        self.generateFlightplansButton = QtGui.QPushButton(self.groupBox_2)
        self.generateFlightplansButton.setIcon(icon)
        self.generateFlightplansButton.setObjectName("generateFlightplansButton")
        self.horizontalLayout_2.addWidget(self.generateFlightplansButton)
        self.generateAircraftButton = QtGui.QPushButton(self.groupBox_2)
        self.generateAircraftButton.setObjectName("generateAircraftButton")
        self.horizontalLayout_2.addWidget(self.generateAircraftButton)
        self.addFleetButton = QtGui.QPushButton(self.groupBox_2)
        self.addFleetButton.setIcon(icon3)
        self.addFleetButton.setObjectName("addFleetButton")
        self.horizontalLayout_2.addWidget(self.addFleetButton)
        self.deleteFleetButton = QtGui.QPushButton(self.groupBox_2)
        self.deleteFleetButton.setIcon(icon4)
        self.deleteFleetButton.setObjectName("deleteFleetButton")
        self.horizontalLayout_2.addWidget(self.deleteFleetButton)
        self.truncateFleetButton = QtGui.QPushButton(self.groupBox_2)
        self.truncateFleetButton.setIcon(icon5)
        self.truncateFleetButton.setObjectName("truncateFleetButton")
        self.horizontalLayout_2.addWidget(self.truncateFleetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.fleetTableWidget = QtGui.QTableWidget(self.fleetTab)
        self.fleetTableWidget.setMinimumSize(QtCore.QSize(1055, 436))
        self.fleetTableWidget.setMaximumSize(QtCore.QSize(3000, 3000))
        self.fleetTableWidget.setAlternatingRowColors(True)
        self.fleetTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.fleetTableWidget.setObjectName("fleetTableWidget")
        self.fleetTableWidget.setColumnCount(7)
        self.fleetTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.fleetTableWidget.setHorizontalHeaderItem(6, item)
        self.fleetTableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.fleetTableWidget.verticalHeader().setVisible(False)
        self.gridLayout_10.addWidget(self.fleetTableWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.fleetTab, "")
        self.aircraftTab = QtGui.QWidget()
        self.aircraftTab.setObjectName("aircraftTab")
        self.gridLayout_11 = QtGui.QGridLayout(self.aircraftTab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.aircraftTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.acTypeEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.acTypeEdit_aircraft.setObjectName("acTypeEdit_aircraft")
        self.gridLayout_4.addWidget(self.acTypeEdit_aircraft, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 2, 1, 1)
        self.designationEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.designationEdit_aircraft.setObjectName("designationEdit_aircraft")
        self.gridLayout_4.addWidget(self.designationEdit_aircraft, 0, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 4, 1, 1)
        self.offsetEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.offsetEdit_aircraft.setObjectName("offsetEdit_aircraft")
        self.gridLayout_4.addWidget(self.offsetEdit_aircraft, 0, 5, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 6, 1, 1)
        self.radiusEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.radiusEdit_aircraft.setObjectName("radiusEdit_aircraft")
        self.gridLayout_4.addWidget(self.radiusEdit_aircraft, 0, 7, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 0, 8, 1, 1)
        self.flTypeEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.flTypeEdit_aircraft.setObjectName("flTypeEdit_aircraft")
        self.gridLayout_4.addWidget(self.flTypeEdit_aircraft, 0, 9, 1, 1)
        self.modelEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.modelEdit_aircraft.setObjectName("modelEdit_aircraft")
        self.gridLayout_4.addWidget(self.modelEdit_aircraft, 1, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 1, 4, 1, 1)
        self.heavyEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.heavyEdit_aircraft.setObjectName("heavyEdit_aircraft")
        self.gridLayout_4.addWidget(self.heavyEdit_aircraft, 1, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 0, 1, 1)
        self.perfClassEdit_aircraft = QtGui.QLineEdit(self.groupBox_3)
        self.perfClassEdit_aircraft.setObjectName("perfClassEdit_aircraft")
        self.gridLayout_4.addWidget(self.perfClassEdit_aircraft, 1, 1, 1, 1)
        self.showButton_aircraft = QtGui.QPushButton(self.groupBox_3)
        self.showButton_aircraft.setIcon(icon1)
        self.showButton_aircraft.setAutoDefault(False)
        self.showButton_aircraft.setDefault(True)
        self.showButton_aircraft.setObjectName("showButton_aircraft")
        self.gridLayout_4.addWidget(self.showButton_aircraft, 1, 7, 1, 1)
        self.clearButton_aircraft = QtGui.QPushButton(self.groupBox_3)
        self.clearButton_aircraft.setIcon(icon2)
        self.clearButton_aircraft.setObjectName("clearButton_aircraft")
        self.gridLayout_4.addWidget(self.clearButton_aircraft, 1, 9, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 0, 0, 1, 1)
        self.labelTotalAircraft = QtGui.QLabel(self.groupBox_3)
        self.labelTotalAircraft.setText("")
        self.labelTotalAircraft.setObjectName("labelTotalAircraft")
        self.gridLayout_7.addWidget(self.labelTotalAircraft, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 1, 0, 1, 1)
        self.labelSelectedAircraft = QtGui.QLabel(self.groupBox_3)
        self.labelSelectedAircraft.setText("")
        self.labelSelectedAircraft.setObjectName("labelSelectedAircraft")
        self.gridLayout_7.addWidget(self.labelSelectedAircraft, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_7)
        self.addMissingAircraftButton = QtGui.QPushButton(self.groupBox_3)
        self.addMissingAircraftButton.setObjectName("addMissingAircraftButton")
        self.horizontalLayout_3.addWidget(self.addMissingAircraftButton)
        self.addAircraftButton = QtGui.QPushButton(self.groupBox_3)
        self.addAircraftButton.setIcon(icon3)
        self.addAircraftButton.setObjectName("addAircraftButton")
        self.horizontalLayout_3.addWidget(self.addAircraftButton)
        self.deleteAircraftButton = QtGui.QPushButton(self.groupBox_3)
        self.deleteAircraftButton.setIcon(icon4)
        self.deleteAircraftButton.setObjectName("deleteAircraftButton")
        self.horizontalLayout_3.addWidget(self.deleteAircraftButton)
        self.truncateAircraftButton = QtGui.QPushButton(self.groupBox_3)
        self.truncateAircraftButton.setIcon(icon5)
        self.truncateAircraftButton.setObjectName("truncateAircraftButton")
        self.horizontalLayout_3.addWidget(self.truncateAircraftButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.aircraftTableWidget = QtGui.QTableWidget(self.aircraftTab)
        self.aircraftTableWidget.setMinimumSize(QtCore.QSize(1055, 436))
        self.aircraftTableWidget.setMaximumSize(QtCore.QSize(3000, 3000))
        self.aircraftTableWidget.setAlternatingRowColors(True)
        self.aircraftTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.aircraftTableWidget.setObjectName("aircraftTableWidget")
        self.aircraftTableWidget.setColumnCount(9)
        self.aircraftTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.aircraftTableWidget.setHorizontalHeaderItem(8, item)
        self.aircraftTableWidget.horizontalHeader().setDefaultSectionSize(112)
        self.aircraftTableWidget.verticalHeader().setVisible(False)
        self.gridLayout_11.addWidget(self.aircraftTableWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.aircraftTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 10)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport_fleet = QtGui.QAction(MainWindow)
        self.actionImport_fleet.setObjectName("actionImport_fleet")
        self.actionImport_aircraft = QtGui.QAction(MainWindow)
        self.actionImport_aircraft.setObjectName("actionImport_aircraft")
        self.actionExport_fleet = QtGui.QAction(MainWindow)
        self.actionExport_fleet.setObjectName("actionExport_fleet")
        self.actionExport_aircraft = QtGui.QAction(MainWindow)
        self.actionExport_aircraft.setObjectName("actionExport_aircraft")
        self.actionDump_database = QtGui.QAction(MainWindow)
        self.actionDump_database.setObjectName("actionDump_database")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLoad_database = QtGui.QAction(MainWindow)
        self.actionLoad_database.setObjectName("actionLoad_database")
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_fleet)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_aircraft)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_fleet)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_aircraft)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDump_database)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_database)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.callsignEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.arrAirportEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.acTypeEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.airlineEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.arrTimeEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.depAirportEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.depDayEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.depTimeEdit, QtCore.SIGNAL("returnPressed()"), self.showButton.click)
        QtCore.QObject.connect(self.callsignEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.airlineEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.designationEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.acTypeEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.nrAircraftEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.hubsEdit_fleet, QtCore.SIGNAL("returnPressed()"), self.showButton_fleet.click)
        QtCore.QObject.connect(self.acTypeEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.designationEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.offsetEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.radiusEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.flTypeEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.perfClassEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.heavyEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QObject.connect(self.modelEdit_aircraft, QtCore.SIGNAL("returnPressed()"), self.showButton_aircraft.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Flightgear AI schedule manager", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Flight rules", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Dep. airport", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Arr. airport", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Dep. time", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Arr. time", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Dep. day", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Aircraft type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Flt. level", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Dep. airport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Dep. time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Dep. day", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Ac. type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Arr. time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Arr. airport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Airline", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Total nr. of flights:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Selected flights:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Duplicates:", None, QtGui.QApplication.UnicodeUTF8))
        self.findDupesButton.setText(QtGui.QApplication.translate("MainWindow", "Create duplicate index", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "Add flight", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete flights", None, QtGui.QApplication.UnicodeUTF8))
        self.truncateButton.setText(QtGui.QApplication.translate("MainWindow", "Empty flights table", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flightsTab), QtGui.QApplication.translate("MainWindow", "Flights", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Airline", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton_fleet.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton_fleet.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Number of aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Hubs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Ac. type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Airline:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Total nr. of fleets:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Selected fleets:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateFlightplansButton.setText(QtGui.QApplication.translate("MainWindow", "Generate flight plans", None, QtGui.QApplication.UnicodeUTF8))
        self.generateAircraftButton.setText(QtGui.QApplication.translate("MainWindow", "Generate aircraft conf", None, QtGui.QApplication.UnicodeUTF8))
        self.addFleetButton.setText(QtGui.QApplication.translate("MainWindow", "Add fleet", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFleetButton.setText(QtGui.QApplication.translate("MainWindow", "Delete fleet", None, QtGui.QApplication.UnicodeUTF8))
        self.truncateFleetButton.setText(QtGui.QApplication.translate("MainWindow", "Empty fleet table", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.setSortingEnabled(True)
        self.fleetTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Airline", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Aircraft type", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Nr. aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Hubs", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.fleetTableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fleetTab), QtGui.QApplication.translate("MainWindow", "Fleet", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Ac. Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Fl. Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Heavy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Perf. class", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton_aircraft.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton_aircraft.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Total nr. of aircraft:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Selected aircraft:", None, QtGui.QApplication.UnicodeUTF8))
        self.addMissingAircraftButton.setText(QtGui.QApplication.translate("MainWindow", "Add missing aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.addAircraftButton.setText(QtGui.QApplication.translate("MainWindow", "Add aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAircraftButton.setText(QtGui.QApplication.translate("MainWindow", "Delete aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.truncateAircraftButton.setText(QtGui.QApplication.translate("MainWindow", "Empty aircraft table", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.setSortingEnabled(True)
        self.aircraftTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Ac. Type", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Flight type", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Heavy", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.aircraftTableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aircraftTab), QtGui.QApplication.translate("MainWindow", "Aircraft Types", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "&Import schedules...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "&Export schedules...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "A&bout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_fleet.setText(QtGui.QApplication.translate("MainWindow", "Import &fleet...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_aircraft.setText(QtGui.QApplication.translate("MainWindow", "Import &aircraft...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_fleet.setText(QtGui.QApplication.translate("MainWindow", "Export fleet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_aircraft.setText(QtGui.QApplication.translate("MainWindow", "Export aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDump_database.setText(QtGui.QApplication.translate("MainWindow", "&Dump database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDump_database.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_database.setText(QtGui.QApplication.translate("MainWindow", "&Load database...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

